# Generated by Django 4.2.10 on 2024-03-14 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categorymodel',
            name='tasks',
        ),
    ]
